### ISSUE TITLE
בדיקת המשחק

### ISSUE THREAD

**Issue by michael-lemberger** [Lba-universe/Forgotten_Game#1]
מספרי קסם, נא לתקן:
KeyboardMoverByTile.cs

HotAirBalloons.Add(new Vector3(2.5f, -9.15f, 0f), new Vector3(11.59f, 7.56f, 0f));

**Comment by Benitk** [comment]
fixed, we created new script 
https://github.com/Lba-universe/Forgotten_Game/blob/master/Assets/Scripts/1-tiles/TeleportOnTrigger.cs
